### ISSUE TITLE
duplicate debug if

### ISSUE THREAD

**Issue by schorsch** [cmitsakis/workerpool-go#1]
i read through the code to see if it may fit my needs and stumbled upon this very minor duplication in https://github.com/cmitsakis/workerpool-go/blob/master/main.go#L552

Concerning the debug statements it looks like a local struct method could clean things up. 
```go

// usage 
// => w.debug(fmt.Sprintf("[workerpool/worker%d] finished", w.id))

func (w *worker[I, O, C]) debug(msg string){
	if w.pool.loggerDebug != nil {
		LoggerDebug.Println(msg) //this should also add the \n 
	}
}
```

I am not a go veteran, so i had to lookup some constructs you are using and found some methods are hard to interpret/read. Especially the loop func is quite a bit of magic :-) 
Still i really like the basic ideas and having it encapsulated in a tiny self-contained package is great!

**Comment by cmitsakis** [comment]
I removed the duplicate if. thanks for noticing it.

> Concerning the debug statements it looks like a local struct method could clean things up.
It definitely makes the code more readable, but if debug is disabled you still pay the cost of fmt.Sprintf. Not a big deal but I decided against it.

> Especially the loop func is quite a bit of magic :-)
The pool loop is complex because of the auto-scaling. auto-scaling is a mess created by trial and error to improve it's stability on pipelines. I have to think a more elegant solution.
